def popolaIlDatabase(self):
    self.caricaTessera(10, 34)
    self.caricaTessera(20, 560)
    self.caricaTessera(30, 35)
    self.caricaTessera(40, 0.3)
    self.aggiungiBevanda("A", "Acqua", 0.20)
    self.aggiungiBevanda("C", "Coca", 0.7)
    self.aggiungiBevanda("F", "Fanta", 1)
    self.aggiungiBevanda("B", "Birra", 1)
    self.aggiungiBevanda("K", "Chinotto", 1)
    self.aggiornaColonna(1, "Acqua", -3)
    self.aggiornaColonna(2, "Coca", 40)
    self.aggiornaColonna(3, "Fanta", 40)
    self.aggiornaColonna(4, "Birra", 40)
    self.aggiornaColonna(5, "Chinotto", -10)
    self.aggiornaColonna(6, "Acqua", 40)
    self.aggiornaColonna(7, "Chinotto", 0)